from __future__ import annotations

import io
from pathlib import Path
from typing import Literal

import torch
from fastapi import FastAPI, Query
from fastapi.responses import StreamingResponse
from torchvision.utils import make_grid, save_image

from cifar_models import (
    GaussianDiffusion,
    SimpleDiffusionUNet,
    SmallEnergyModel,
    denormalize_cifar,
    get_device,
    images_to_png_bytes,
    load_weights_if_available,
    sample_ebm_langevin,
)
from model import get_model


app = FastAPI(
    title="Assignment 4 Generative Model API",
    description=(
        "FastAPI deployment for MNIST GAN, CIFAR-10 Energy-Based Model, "
        "and CIFAR-10 Diffusion Model."
    ),
    version="2.0",
)

DEVICE = get_device()
MODELS_DIR = Path("models")

# Keep the Assignment 3 GAN endpoint working.
GAN_MODEL_PATH = Path("mnist_generator.pth")
gan_model = get_model("GAN").to(DEVICE)
if GAN_MODEL_PATH.exists():
    gan_model.generator.load_state_dict(torch.load(GAN_MODEL_PATH, map_location=DEVICE))
gan_model.eval()

# Assignment 4 models. If trained weights are not present, the API still starts
# with randomly initialized models so the Docker endpoint can be tested.
ebm_model = SmallEnergyModel().to(DEVICE)
ebm_weights_loaded = load_weights_if_available(
    ebm_model,
    MODELS_DIR / "ebm_cifar10.pth",
    DEVICE,
)
ebm_model.eval()

diffusion_model = SimpleDiffusionUNet().to(DEVICE)
diffusion_weights_loaded = load_weights_if_available(
    diffusion_model,
    MODELS_DIR / "diffusion_cifar10.pth",
    DEVICE,
)
diffusion_model.eval()
diffusion_process = GaussianDiffusion(timesteps=100, device=DEVICE)


def mnist_grid_response(images: torch.Tensor, filename: str) -> StreamingResponse:
    images = ((images.detach().cpu() + 1) / 2).clamp(0, 1)
    grid = make_grid(images, nrow=min(8, images.shape[0]), padding=2)
    image_buffer = io.BytesIO()
    save_image(grid, image_buffer, format="PNG")
    image_buffer.seek(0)
    return StreamingResponse(
        image_buffer,
        media_type="image/png",
        headers={"Content-Disposition": f'inline; filename="{filename}"'},
    )


def cifar_grid_response(images: torch.Tensor, filename: str) -> StreamingResponse:
    image_buffer = images_to_png_bytes(images)
    return StreamingResponse(
        image_buffer,
        media_type="image/png",
        headers={"Content-Disposition": f'inline; filename="{filename}"'},
    )


@app.get("/")
def home():
    return {
        "message": "Assignment 4 API is running.",
        "device": str(DEVICE),
        "models": {
            "gan_mnist": {"endpoint": "/generate/gan?num_samples=10"},
            "ebm_cifar10": {
                "endpoint": "/generate/ebm?num_samples=10&steps=40",
                "weights_loaded": ebm_weights_loaded,
            },
            "diffusion_cifar10": {
                "endpoint": "/generate/diffusion?num_samples=10&steps=50",
                "weights_loaded": diffusion_weights_loaded,
            },
        },
    }


@app.get("/health")
def health():
    return {"status": "ok", "device": str(DEVICE)}


@app.get("/generate")
def generate(
    model: Literal["gan", "ebm", "diffusion"] = Query(default="diffusion"),
    num_samples: int = Query(default=10, ge=1, le=64),
    steps: int = Query(default=40, ge=1, le=100),
):
    """Unified image-generation endpoint for all implemented models."""

    if model == "gan":
        return generate_gan(num_samples=num_samples)
    if model == "ebm":
        return generate_ebm(num_samples=num_samples, steps=steps)
    return generate_diffusion(num_samples=num_samples, steps=steps)


@app.get("/generate/gan")
def generate_gan(num_samples: int = Query(default=10, ge=1, le=64)):
    """Return a PNG grid of MNIST digits generated by the Assignment 3 GAN."""

    with torch.no_grad():
        noise = torch.randn(num_samples, gan_model.latent_dim, device=DEVICE)
        generated_images = gan_model.generator(noise)
    return mnist_grid_response(generated_images, "generated_mnist_gan.png")


@app.get("/generate/ebm")
def generate_ebm(
    num_samples: int = Query(default=10, ge=1, le=64),
    steps: int = Query(default=40, ge=1, le=100),
):
    """Return CIFAR-sized samples generated with EBM Langevin dynamics."""

    samples = sample_ebm_langevin(
        model=ebm_model,
        num_samples=num_samples,
        device=DEVICE,
        steps=steps,
    )
    return cifar_grid_response(samples, "generated_cifar10_ebm.png")


@app.get("/generate/diffusion")
def generate_diffusion(
    num_samples: int = Query(default=10, ge=1, le=32),
    steps: int = Query(default=50, ge=1, le=100),
):
    """Return CIFAR-sized samples generated by reverse diffusion."""

    samples = diffusion_process.sample(
        model=diffusion_model,
        num_samples=num_samples,
        device=DEVICE,
        sampling_steps=steps,
    )
    return cifar_grid_response(denormalize_cifar(samples), "generated_cifar10_diffusion.png")
